describe('LOGIN', () => {
  beforeEach(()=>{
    cy.visit('https://automationexercise.com/login')
  })

  it('Verify user can signup successfully', () => {
    cy.get('.signup-form').should('exist')
    cy.get('[data-qa="signup-name"]').should('be.empty').type('oluwaseun')
    cy.get('[data-qa="signup-name"]').should('have.value', 'oluwaseun')
    cy.get('[data-qa="signup-email"]').should('be.empty').type('s2eunfunmi112@gmail.com')
    cy.get('[data-qa="signup-email"]').should('have.value','s2eunfunmi112@gmail.com')
    cy.get('[data-qa="signup-button"]').should('be.visible')
    cy.get('[data-qa="signup-button"]').click()
    cy.get('#id_gender1').click()
    cy.get('#id_gender1').should('be.checked')
    cy.get('[data-qa="password"]').should('be.empty').type('Tolulope2')
    cy.get('[data-qa="password"]').should('have.value', 'Tolulope2')
    cy.get('#days').select(12)
    cy.get('#days').should('have.value', 12)
    cy.get('#months').select(4)
    cy.get('#months').should('have.value', 4)
    cy.get('[data-qa="years"]').select('1992')
    cy.get('[data-qa="years"]').should('have.value', '1992')
    cy.get('#first_name').should('be.empty').type('Toheeb')
    cy.get('#first_name').should('have.value', 'Toheeb')
    cy.get('#last_name').should('be.empty').type('Paul')
    cy.get('#last_name').should('have.value','Paul')
    cy.get('[data-qa="company"]').should('be.empty').type('dangote')
    cy.get('[data-qa="company"]').should('have.value', 'dangote')
    cy.get('#address1').should('be.empty').type('245 creekwood cove ln')
    cy.get('#address1').should('have.value', '245 creekwood cove ln')
    cy.get('#country').select('United States')
    cy.get('#country').should('have.value', 'United States')
    cy.get('[data-qa="state"]').should('be.empty').type('tennessee')
    cy.get('[data-qa="state"]').should('have.value','tennessee')
    cy.get('[data-qa="city"]').should('be.empty').type('lenoir city')
    cy.get('[data-qa="city"]').should('have.value', 'lenoir city')
    cy.get('[data-qa="zipcode"]').should('be.empty').type(37772)
    cy.get('[data-qa="zipcode"]').should('have.value', 37772)
    cy.get('[data-qa="mobile_number"]').should('be.empty').type(+14328742763)
        cy.get('[data-qa="mobile_number"]').should('have.value', +14328742763)
    cy.contains('Create Account').should('exist')
     cy.contains('Create Account').click()
   })

   it.only('Verify successful login and add to cart', () => {
     cy.get('.shop-menu > .nav > :nth-child(4) > a').click()
     cy.get('.login-form').should('exist')
     cy.get('[data-qa="login-email"]').should('be.empty').type('seunfunmi11@gmail.com')
     cy.get('[data-qa="login-email"]').should('have.value', 'seunfunmi11@gmail.com')
     cy.get('[data-qa="login-password"]').should('be.empty').type('Tolulope2')
     cy.get('[data-qa="login-password"]').should('have.value', 'Tolulope2')
     cy.get('[data-qa="login-button"]').should('exist')
     cy.get('[data-qa="login-button"]').click()
     cy.get('.features_items').should('be.visible')
     cy.get(':nth-child(4) > .product-image-wrapper > .single-products > .productinfo > .btn').contains('Add to cart').click()
     cy.contains('Continue Shopping').click()
     cy.get(':nth-child(11) > .product-image-wrapper > .single-products > .productinfo > .btn').contains('Add to cart').click()
     cy.contains('Continue Shopping').click()
     cy.get(':nth-child(17) > .product-image-wrapper > .single-products > .productinfo > .btn').contains('Add to cart').click()
     cy.contains('Continue Shopping').click()
     cy.get(':nth-child(25) > .product-image-wrapper > .single-products > .productinfo > .btn').contains('Add to cart').click()
     cy.contains('Continue Shopping').click()
   })

   
 })